name: Kuzenbot Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,16 * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie kodu repozytorium
      uses: actions/checkout@v4

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalacja wymaganych bibliotek
      run: pip install -r requirements.txt

    - name: Run Scraper
      env:
        ORACLE_IP: ${{ secrets.ORACLE_IP }}
      run: python run.py
